
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightASIGleftSUMARESTAleftMULTDIVrightUMINUSAND ASIG BEGIN BOOLEAN COMA COMMENT DECL DIV ELSE END ERROR ID IF IGUAL INT INTEGER LPAREN MAYOR MAYORIGUAL MENOR MENORIGUAL MULT NIGUAL NOT OR PC PROG RESTA RPAREN STRING SUMAstatement : expressionstatement : ID ASIG expression\n                 | INT ID ASIG expressionexpression : expression SUMA expression\n                  | expression RESTA expression\n                  | expression MULT expression\n                  | expression DIV expressionexpression : RESTA expression %prec UMINUSexpression : LPAREN expression RPARENexpression : INTEGERexpression : ID'
    
_lr_action_items = {'ID':([0,4,5,6,8,9,10,11,12,22,],[3,13,15,15,15,15,15,15,15,15,]),'INT':([0,],[4,]),'RESTA':([0,2,3,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,22,23,24,],[5,9,-11,5,5,-10,5,5,5,5,5,-8,-11,9,-4,-5,-6,-7,9,5,-9,9,]),'LPAREN':([0,5,6,8,9,10,11,12,22,],[6,6,6,6,6,6,6,6,6,]),'INTEGER':([0,5,6,8,9,10,11,12,22,],[7,7,7,7,7,7,7,7,7,]),'$end':([1,2,3,7,14,15,17,18,19,20,21,23,24,],[0,-1,-11,-10,-8,-11,-4,-5,-6,-7,-2,-9,-3,]),'SUMA':([2,3,7,14,15,16,17,18,19,20,21,23,24,],[8,-11,-10,-8,-11,8,-4,-5,-6,-7,8,-9,8,]),'MULT':([2,3,7,14,15,16,17,18,19,20,21,23,24,],[10,-11,-10,-8,-11,10,10,10,-6,-7,10,-9,10,]),'DIV':([2,3,7,14,15,16,17,18,19,20,21,23,24,],[11,-11,-10,-8,-11,11,11,11,-6,-7,11,-9,11,]),'ASIG':([3,13,],[12,22,]),'RPAREN':([7,14,15,16,17,18,19,20,23,],[-10,-8,-11,23,-4,-5,-6,-7,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,5,6,8,9,10,11,12,22,],[2,14,16,17,18,19,20,21,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expr','YAAOaP.py',15),
  ('statement -> ID ASIG expression','statement',3,'p_statement_assign','YAAOaP.py',19),
  ('statement -> INT ID ASIG expression','statement',4,'p_statement_assign','YAAOaP.py',20),
  ('expression -> expression SUMA expression','expression',3,'p_expression_binop','YAAOaP.py',29),
  ('expression -> expression RESTA expression','expression',3,'p_expression_binop','YAAOaP.py',30),
  ('expression -> expression MULT expression','expression',3,'p_expression_binop','YAAOaP.py',31),
  ('expression -> expression DIV expression','expression',3,'p_expression_binop','YAAOaP.py',32),
  ('expression -> RESTA expression','expression',2,'p_expression_uminus','YAAOaP.py',43),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','YAAOaP.py',47),
  ('expression -> INTEGER','expression',1,'p_expression_integer','YAAOaP.py',51),
  ('expression -> ID','expression',1,'p_expression_id','YAAOaP.py',55),
]
